Rat 30 bmp crawler
LukasTinnes/sPyRat pull request #6
Opened 2022-02-07 00:54 UTC by WeGlove

Added BMP Crawler for BITIMAPNFO V3 and V5

2022-02-13 19:25 UTC, WeGlove commented
Rechtschreibfehler in Byteoperations

2022-02-13 19:34 UTC, WeGlove commented
seek an anfang der loop

2022-02-13 19:50 UTC, LukasTinnes requested changes
Neue Methoden durch anderen PR hinzugekommen. Hinzufügen.

2022-02-17 20:26 UTC, LukasTinnes approved these changes
lgtm

2022-02-17 20:27 UTC, merged